// src/utils/words.ts

export const WORD_PAIRS = [
  // --- WORD VERSION (Witty / Blurry / Chaotic) ---
  { majority: "Your 5% phone battery", impostor: "A charging cable that only works at a 37° angle", type: "word" },
  { majority: "“We need to talk.” message", impostor: "A calendar invite titled “Quick Sync” (no agenda)", type: "word" },
  { majority: "Unskippable tutorial", impostor: "Unskippable ad (louder than your thoughts)", type: "word" },
  { majority: "Group chat “Seen”", impostor: "Typing bubble that vanishes", type: "word" },
  { majority: "Freshly mopped floor", impostor: "New white shoes", type: "word" },
  { majority: "Rice cooker click", impostor: "Microwave beep at 2 AM", type: "word" },
  { majority: "Tupperware with no lid", impostor: "A single sock", type: "word" },
  { majority: "Sari-sari store utang list", impostor: "0% installment you forgot to cancel", type: "word" },
  { majority: "The one strong electric fan", impostor: "The one weak Wi-Fi bar", type: "word" },
  { majority: "Plastic labo bag", impostor: "Paper straw that gives up", type: "word" },
  { majority: "Barangay siren", impostor: "Car alarm nobody claims", type: "word" },
  { majority: "“Last chance” sale banner", impostor: "“Limited seats” webinar ad", type: "word" },
  { majority: "Phone autocorrect", impostor: "Voice-to-text betrayal", type: "word" },
  { majority: "Screenshot of a receipt", impostor: "Screenshot of a QR code (cropped)", type: "word" },
  { majority: "Unread emails (999+)", impostor: "Unwatched “Watch Later” playlist (infinite)", type: "word" },
  { majority: "Laundry forgotten in the washer", impostor: "Iced coffee abandoned on the desk", type: "word" },
  { majority: "Wallet with too many cards", impostor: "Keychain with one mystery key", type: "word" },
  { majority: "Expired OTP", impostor: "Expired parking ticket", type: "word" },
  { majority: "Brownout candle", impostor: "Flashlight with no batteries", type: "word" },
  { majority: "Extension cord spaghetti", impostor: "Earphones in pocket (knot wizardry)", type: "word" },
  { majority: "Mysterious fridge smell", impostor: "Mysterious group chat tension", type: "word" },
  { majority: "Exact change (mythical)", impostor: "Jeepney sukli that never arrives", type: "word" },
  { majority: "Traffic on EDSA", impostor: "Buffering on 480p", type: "word" },
  { majority: "“Bukas na ’yan.”", impostor: "“I’ll reply later.”", type: "word" },
  { majority: "Overheated laptop fan", impostor: "Overheated group project GC", type: "word" },
  { majority: "Broken umbrella in bag", impostor: "Broken promise in Notes app", type: "word" },
  { majority: "Sticky keyboard", impostor: "Sticky fast-food table", type: "word" },
  { majority: "Karaoke mic", impostor: "Zoom unmute panic", type: "word" },
  { majority: "Raining during laundry day", impostor: "Low battery during presentation day", type: "word" },
  { majority: "New haircut", impostor: "New username", type: "word" },
  { majority: "Walang signal", impostor: "Walang laman GCash", type: "word" },
  { majority: "5-minute “last game”", impostor: "5-minute “last episode”", type: "word" },
  { majority: "Your “clean desk” illusion", impostor: "Your “I’ll sleep early” illusion", type: "word" },
  { majority: "Spam calls", impostor: "Spam group chat stickers", type: "word" },
  { majority: "Notebook margin doodles", impostor: "Code comments that lie", type: "word" },
  { majority: "“Out of stock” notification", impostor: "“Delivered” but not at your house", type: "word" },
  { majority: "School ID photo", impostor: "Passport photo", type: "word" },
  { majority: "Free taste sample", impostor: "Free trial you forgot to cancel", type: "word" },
  { majority: "Queue number ticket", impostor: "Barangay clearance slip", type: "word" },
  { majority: "Crush in your story viewers", impostor: "Ex in your story viewers", type: "word" },
  { majority: "Aesthetic study setup", impostor: "Aesthetic coffee setup", type: "word" },
  { majority: "Keyboard clacks", impostor: "Heels on hallway tiles", type: "word" },
  { majority: "Piso coin", impostor: "The remote’s last surviving battery", type: "word" },
  { majority: "Nostalgic OPM playlist", impostor: "Nostalgic Windows startup sound", type: "word" },
  { majority: "MRT “beep-beep”", impostor: "ATM “beep-beep”", type: "word" },
  { majority: "Auntie asking “may jowa ka na?”", impostor: "App asking “rate us 5 stars”", type: "word" },
  { majority: "Aircon remote that disappears", impostor: "TV remote that disappears", type: "word" },
  { majority: "Leftover spaghetti", impostor: "Leftover deadlines", type: "word" },
  { majority: "Sunscreen you never reapply", impostor: "Password you never update", type: "word" },
  { majority: "Powerbank brick", impostor: "Textbook brick", type: "word" },
  { majority: "Random bruise you can’t explain", impostor: "Random expense you can’t explain", type: "word" },
  { majority: "Stickered water bottle", impostor: "Stickered laptop", type: "word" },
  { majority: "Last 1% of ketchup", impostor: "Last 1% of toothpaste", type: "word" },
  { majority: "Drawer full of chargers", impostor: "Shoe box full of wires", type: "word" },
  { majority: "“Add to cart” therapy", impostor: "“Download another app” therapy", type: "word" },
  { majority: "Receipt in your pocket", impostor: "Screenshot in your gallery", type: "word" },
  { majority: "Under construction website", impostor: "Bukas na store sign", type: "word" },
  { majority: "Pinoy “come here” hand gesture", impostor: "Browser tab “are you still watching?”", type: "word" },
  { majority: "“Ma, where’s my—”", impostor: "“Boss, where’s the—”", type: "word" },
  { majority: "UV Express ride", impostor: "Loading screen ride", type: "word" },
  { majority: "Waze rerouting", impostor: "Life rerouting", type: "word" },
  { majority: "“Magkano?”", impostor: "“HM?”", type: "word" },
  { majority: "Phone case yellowing", impostor: "White shirt collar yellowing", type: "word" },
  { majority: "New notebook first page", impostor: "New repo first commit", type: "word" },
  { majority: "“You’re on mute.”", impostor: "“Your mic is echoing.”", type: "word" },
  { majority: "Spam folder", impostor: "“Archived” feelings", type: "word" },
  { majority: "Sobrang lamig sa aircon", impostor: "Sobrang init sa commute", type: "word" },
  { majority: "Mystery Tupperware in the ref", impostor: "Mystery file on your desktop", type: "word" },
  { majority: "Crush’s “haha” react", impostor: "Professor’s “see me after class”", type: "word" },
  { majority: "One missing puzzle piece", impostor: "One missing semicolon", type: "word" },
  { majority: "Unreturned Tupperware", impostor: "Unreturned book", type: "word" },
  { majority: "Jeepney fare increase", impostor: "Subscription price increase", type: "word" },
  { majority: "Wikipedia “one more link” spiral", impostor: "TikTok “For You” spiral", type: "word" },
  { majority: "“Sorry late reply”", impostor: "“Sorry late submission”", type: "word" },
  { majority: "One last sip of milk tea", impostor: "One last scroll before sleep", type: "word" },
  { majority: "Low tide beach walk", impostor: "Empty campus walk", type: "word" },
  { majority: "Barangay basketball league", impostor: "Office ping-pong league", type: "word" },
  { majority: "Lunchbox you forgot", impostor: "Charger you forgot", type: "word" },
  { majority: "Christmas lights in February", impostor: "Christmas song in July", type: "word" },
  { majority: "Glitter glue", impostor: "Printer ink (stains your soul)", type: "word" },
  { majority: "Hot pandesal", impostor: "Warm hotel towel", type: "word" },
  { majority: "Sunog na rice", impostor: "Burnt toast", type: "word" },
  { majority: "Spicy noodles", impostor: "Spicy comment section", type: "word" },
  { majority: "The “quick favor” from a friend", impostor: "The “one last request” from a groupmate", type: "word" },
  { majority: "Dirty whiteboard eraser", impostor: "Dirty browser cache", type: "word" },
  { majority: "Elevator awkward silence", impostor: "Hallway crush encounter", type: "word" },
  { majority: "Toothpick after lechon", impostor: "Floss after popcorn", type: "word" },
  { majority: "Christmas bonus", impostor: "Tax refund", type: "word" },
  { majority: "Mom’s plastic container stash", impostor: "Dad’s cable stash", type: "word" },
  { majority: "Tricycle bargaining", impostor: "Facebook Marketplace bargaining", type: "word" },
  { majority: "A4 bond paper", impostor: "Printer jam", type: "word" },
  { majority: "Slack ping", impostor: "Messenger ping", type: "word" },
  { majority: "Forgotten umbrella at the office", impostor: "Forgotten jacket at the cinema", type: "word" },
  { majority: "“Bawal plastic” day", impostor: "“Bawal spoilers” day", type: "word" },
  { majority: "K-drama cliffhanger", impostor: "Game update cliffhanger", type: "word" },
  { majority: "Spotify “Discover Weekly”", impostor: "YouTube “Recommended”", type: "word" },
  { majority: "Old family photo album", impostor: "Old chat archive", type: "word" },
  { majority: "Barangay fiesta banderitas", impostor: "Hackathon sponsor banners", type: "word" },
  { majority: "3-in-1 coffee", impostor: "Instant ramen", type: "word" },
  { majority: "Freshly sharpened pencil", impostor: "Freshly updated drivers", type: "word" },
  { majority: "Sneeze in a quiet room", impostor: "Notification sound in a quiet room", type: "word" },
  { majority: "Handwritten notes", impostor: "Handwritten apology", type: "word" },
  { majority: "Chismis", impostor: "Patch notes", type: "word" },
  { majority: "“Asan na?”", impostor: "“ETA?”", type: "word" },
  { majority: "Jeepney “para po”", impostor: "Zoom “leave meeting”", type: "word" },
  { majority: "Alarm you snooze 7 times", impostor: "Deadline you “extend” 7 times", type: "word" },
  { majority: "Unpaid group dinner split", impostor: "Unpaid group project contribution", type: "word" },
  { majority: "Paper cut", impostor: "Tongue burn from hot soup", type: "word" },
  { majority: "Random “Hi” from unknown number", impostor: "Random “Can you hop on a call?”", type: "word" },
  { majority: "Sticker shock at grocery", impostor: "Sticker shock at tuition fee", type: "word" },
  { majority: "Cold pizza at 3 AM", impostor: "Cold tapsilog at 3 AM", type: "word" },
  { majority: "Free Wi-Fi (needs login)", impostor: "Free parking (needs validation)", type: "word" },
  { majority: "Tiny hotel soap", impostor: "Tiny hotel water bottle", type: "word" },
  { majority: "Keyboard shortcut you forget", impostor: "Password you forget", type: "word" },
  { majority: "The “Update now” button", impostor: "The “Remind me tomorrow” button", type: "word" },
  { majority: "Lanyard you spin", impostor: "Pen you click", type: "word" },
  { majority: "“Out of office” auto-reply", impostor: "“Low battery” auto-warning", type: "word" },
  { majority: "New shoes squeak", impostor: "New chair squeak", type: "word" },
  { majority: "Screen protector bubble", impostor: "Phone case dust speck", type: "word" },
  { majority: "ATM swallowed your card", impostor: "Browser swallowed your tabs", type: "word" },
  { majority: "Packed MRT", impostor: "Packed browser tabs", type: "word" },
  { majority: "“Titingin lang”", impostor: "“I’ll commit after I test”", type: "word" },
  { majority: "GCash “System Maintenance”", impostor: "Printer “Offline”", type: "word" },
  { majority: "Fried chicken crumbs", impostor: "Keyboard crumbs", type: "word" },
  { majority: "One charger for five devices", impostor: "One extension cord for five outlets", type: "word" },
  { majority: "Silent mode ON", impostor: "Do Not Disturb ON (but for emotions)", type: "word" },
  { majority: "A “for later” pile", impostor: "A “for next sem” folder", type: "word" },
  { majority: "Ice in your drink melting", impostor: "Motivation in week 2 fading", type: "word" },
  { majority: "Sudden thunder", impostor: "Sudden notification: “Your storage is full”", type: "word" },
  { majority: "Someone borrowing your pen", impostor: "Someone borrowing your charger", type: "word" },
  { majority: "Coffee breath", impostor: "Garlic breath", type: "word" },
  { majority: "A cracked phone screen", impostor: "A cracked “friendship” after group work", type: "word" },
  { majority: "Jeepney signboard “Kaliwa”", impostor: "Google Maps saying “Recalculating”", type: "word" },
  { majority: "A “nice” group photo", impostor: "A “nice” resume", type: "word" },
  { majority: "Holiday weight gain", impostor: "Holiday email backlog", type: "word" },
  { majority: "Tita’s unsolicited advice", impostor: "LinkedIn’s unsolicited job alerts", type: "word" },
  { majority: "A soap opera plot twist", impostor: "A software update plot twist", type: "word" },
  { majority: "The last chair in the room", impostor: "The last seat in the cinema", type: "word" },
  { majority: "A “low effort” meme", impostor: "A “low effort” excuse", type: "word" },
  { majority: "A “Hi sir” email", impostor: "A “Hi po” message", type: "word" },
  { majority: "A plastic spoon that snaps", impostor: "A cheap zipper that snaps", type: "word" },
  { majority: "The one fork missing at home", impostor: "The one sock missing in laundry", type: "word" },
  { majority: "A “pwede na” haircut", impostor: "A “pwede na” code fix", type: "word" },
  { majority: "A “kain tayo” invite", impostor: "A “tara call” invite", type: "word" },
  { majority: "That one blanket you hoard", impostor: "That one hoodie you wear “for comfort”", type: "word" },
  { majority: "Eraser shavings", impostor: "Parmesan sprinkles", type: "word" },
  { majority: "Overly aggressive hand dryer", impostor: "Taxi aircon set to “Antarctica”", type: "word" },
  { majority: "A receipt stapled to a warranty", impostor: "A manual you instantly throw away", type: "word" },
  { majority: "Phone camera “beauty mode”", impostor: "Photo booth lighting (lies in HD)", type: "word" },
  { majority: "A charger borrowed “sandali lang”", impostor: "A book borrowed “promise ibabalik”", type: "word" },
  { majority: "“Minimum spend to use voucher”", impostor: "“Minimum words to pass the rubric”", type: "word" },
  { majority: "“Ayaw mag-load”", impostor: "“Ayaw mag-compile”", type: "word" },
  { majority: "A tab you refuse to close", impostor: "A door you refuse to pull (it says PUSH)", type: "word" },
  { majority: "A plastic cover on the remote", impostor: "A plastic cover on the sofa", type: "word" },
  { majority: "Sinigang na maasim (good)", impostor: "Sour face in a selfie (not good)", type: "word" },
  { majority: "Newly washed bedsheets", impostor: "Newly updated OS (same fresh feeling)", type: "word" },
  { majority: "Water jug running empty", impostor: "Printer ink running empty", type: "word" },
  { majority: "A long line at the cashier", impostor: "A long loading bar at 99%", type: "word" },
  { majority: "A “cute” nickname you regret", impostor: "A “funny” username you regret", type: "word" },
  { majority: "A “pabili” request from family", impostor: "A “paki-merge” request from teammate", type: "word" },
  { majority: "A suspiciously quiet classroom", impostor: "A suspiciously quiet production server", type: "word" },
  { majority: "A birthday candle you can’t blow out", impostor: "A stubborn jar lid you can’t open", type: "word" },
  { majority: "The one photocard in your wallet", impostor: "The one random keychain you keep", type: "word" },
  { majority: "A “please bring 1x1” reminder", impostor: "A “please attach screenshot” reminder", type: "word" },
  { majority: "Tupperware marked “DO NOT TOUCH”", impostor: "A folder named “FINAL_FINAL”", type: "word" },
  { majority: "A cracked plastic chair", impostor: "A cracked “free” app", type: "word" },
  { majority: "A pencil that keeps breaking", impostor: "A connection that keeps dropping", type: "word" },
  { majority: "The smell of rain on pavement", impostor: "The smell of new printed paper", type: "word" },
  { majority: "A sari-sari store bell", impostor: "A hotel lobby bell", type: "word" },
  { majority: "A “sige” that means “no”", impostor: "A “noted” that means “never”", type: "word" },

  // --- QUESTION VERSION (Witty / Blurry) ---
  {
    majority: "What’s your go-to excuse for being late?",
    impostor: "What’s your go-to excuse for leaving early?",
    type: "question",
  },
  {
    majority: "What’s the most “adult” thing you did this week?",
    impostor: "What’s the most “childish” thing you did this week?",
    type: "question",
  },
  {
    majority: "What’s a smell that instantly takes you back?",
    impostor: "What’s a sound that instantly takes you back?",
    type: "question",
  },
  {
    majority: "What do you pretend you understand?",
    impostor: "What do you actually understand but pretend you don’t?",
    type: "question",
  },
  {
    majority: "If your life had a loading screen, what would it say?",
    impostor: "If your life had a pop-up warning, what would it say?",
    type: "question",
  },
  {
    majority: "What’s a rule you follow even when nobody’s watching?",
    impostor: "What’s a rule you break only when nobody’s watching?",
    type: "question",
  },
  {
    majority: "What’s the most random item in your bag right now?",
    impostor: "What’s the most random item on your desk right now?",
    type: "question",
  },
  {
    majority: "What’s your “I’m productive” illusion?",
    impostor: "What’s your “I’m fine” illusion?",
    type: "question",
  },
  {
    majority: "What’s a tiny thing that annoys you way too much?",
    impostor: "What’s a tiny thing that makes you happy way too much?",
    type: "question",
  },
  {
    majority: "What’s a food you only like in one specific form?",
    impostor: "What’s a food you like… except in one specific form?",
    type: "question",
  },
  {
    majority: "What do you always say you’ll do “tomorrow”?",
    impostor: "What do you always say you’ll do “after this one thing”?",
    type: "question",
  },
  {
    majority: "What’s your personal “system maintenance” sign?",
    impostor: "What’s your personal “low battery” sign?",
    type: "question",
  },
  {
    majority: "What’s something you hoard “just in case”?",
    impostor: "What’s something you throw away immediately?",
    type: "question",
  },
  {
    majority: "What’s a compliment you never forget?",
    impostor: "What’s an insult you never forget?",
    type: "question",
  },
  {
    majority: "What’s a phrase you overuse in chat?",
    impostor: "What’s an emoji you overuse in chat?",
    type: "question",
  },
  {
    majority: "If you had a theme song, what genre would it be?",
    impostor: "If you had a theme song, what would the title be?",
    type: "question",
  },
  {
    majority: "What’s the safest risk you’ve taken?",
    impostor: "What’s the riskiest safe choice you’ve made?",
    type: "question",
  },
  {
    majority: "What’s your go-to comfort drink?",
    impostor: "What’s your go-to comfort noise?",
    type: "question",
  },
  {
    majority: "What’s the best “budol” you’ve experienced?",
    impostor: "What’s the worst “budol” you’ve experienced?",
    type: "question",
  },
  {
    majority: "What’s a habit you’re proud of?",
    impostor: "What’s a habit you’re trying to delete?",
    type: "question",
  },
  {
    majority: "What’s a task you can do fast but hate doing?",
    impostor: "What’s a task you love doing but do slowly?",
    type: "question",
  },
  {
    majority: "What’s something you always forget to bring?",
    impostor: "What’s something you always remember to bring?",
    type: "question",
  },
  {
    majority: "What’s your favorite “small win” feeling?",
    impostor: "What’s your least favorite “small loss” feeling?",
    type: "question",
  },
  {
    majority: "What’s a movie you can rewatch anytime?",
    impostor: "What’s a scene you refuse to rewatch?",
    type: "question",
  },
  {
    majority: "What’s your default order at a fast-food place?",
    impostor: "What’s your “I’m trying to be healthy” order?",
    type: "question",
  },
  {
    majority: "What’s a game mechanic you love?",
    impostor: "What’s a game mechanic you tolerate?",
    type: "question",
  },
  {
    majority: "What’s a word you mispronounced for years?",
    impostor: "What’s a word you still avoid saying out loud?",
    type: "question",
  },
  {
    majority: "What’s a feature you wish humans had?",
    impostor: "What’s a feature you wish apps had?",
    type: "question",
  },
  {
    majority: "If you had a superpower, what would you use it for?",
    impostor: "If you had a superpower, what would you ban yourself from doing?",
    type: "question",
  },
  {
    majority: "What’s something you can’t eat without making a mess?",
    impostor: "What’s something you can’t eat without slowing down?",
    type: "question",
  },
  {
    majority: "What’s a purchase you justified with “deserve ko ’to”?",
    impostor: "What’s a purchase you regretted within 24 hours?",
    type: "question",
  },
  {
    majority: "What’s your favorite “lazy” meal?",
    impostor: "What’s your favorite “lazy” excuse?",
    type: "question",
  },
  {
    majority: "What’s a sound that means “good news”?",
    impostor: "What’s a sound that means “bad news”?",
    type: "question",
  },
  {
    majority: "What’s your weirdest talent?",
    impostor: "What’s your most useless skill?",
    type: "question",
  },
  {
    majority: "What’s a topic you can talk about for hours?",
    impostor: "What’s a topic you refuse to talk about for hours?",
    type: "question",
  },
  {
    majority: "What’s the nicest lie you’ve told?",
    impostor: "What’s the harshest truth you’ve said politely?",
    type: "question",
  },
  {
    majority: "What’s your “I’m about to snap” warning sign?",
    impostor: "What’s your “I’m about to sleep” warning sign?",
    type: "question",
  },
  {
    majority: "What’s something you’d put on a personal warning label?",
    impostor: "What’s something you’d put on a personal user manual?",
    type: "question",
  },
  {
    majority: "What’s your favorite place to waste time?",
    impostor: "What’s your favorite way to save time?",
    type: "question",
  },
  {
    majority: "What’s the last thing you Google’d in panic?",
    impostor: "What’s the last thing you Google’d out of curiosity?",
    type: "question",
  },
];

export const getRandomWordPair = () => {
  const index = Math.floor(Math.random() * WORD_PAIRS.length);
  return WORD_PAIRS[index];
}
